name:                 codewars
version:              0.1.0.0
visibility:           public
id:                   codewars-0.1.0.0-BM3WsMXuX7NDIxbgGOC4Vh
key:                  codewars-0.1.0.0-BM3WsMXuX7NDIxbgGOC4Vh
license:              BSD-3-Clause
maintainer:           joaofsoares@yahoo.com
author:               joaofsoares
abi:                  7af1dd64efd1593c8dcb3a00189d403c
exposed:              True
exposed-modules:      AreTheyTheSame
import-dirs:
    /Users/joaofelipesoares/Development/haskell/haskell-learn/codewars/.stack-work/install/aarch64-osx/5fcdde4fcb2d3e421d904e2b141cb989eb2b75c214fa897a4eb7fb6a71f865ec/9.4.5/lib/aarch64-osx-ghc-9.4.5/codewars-0.1.0.0-BM3WsMXuX7NDIxbgGOC4Vh

library-dirs:
    /Users/joaofelipesoares/Development/haskell/haskell-learn/codewars/.stack-work/install/aarch64-osx/5fcdde4fcb2d3e421d904e2b141cb989eb2b75c214fa897a4eb7fb6a71f865ec/9.4.5/lib/aarch64-osx-ghc-9.4.5/codewars-0.1.0.0-BM3WsMXuX7NDIxbgGOC4Vh

library-dirs-static:
    /Users/joaofelipesoares/Development/haskell/haskell-learn/codewars/.stack-work/install/aarch64-osx/5fcdde4fcb2d3e421d904e2b141cb989eb2b75c214fa897a4eb7fb6a71f865ec/9.4.5/lib/aarch64-osx-ghc-9.4.5/codewars-0.1.0.0-BM3WsMXuX7NDIxbgGOC4Vh

dynamic-library-dirs:
    /Users/joaofelipesoares/Development/haskell/haskell-learn/codewars/.stack-work/install/aarch64-osx/5fcdde4fcb2d3e421d904e2b141cb989eb2b75c214fa897a4eb7fb6a71f865ec/9.4.5/lib/aarch64-osx-ghc-9.4.5

data-dir:
    /Users/joaofelipesoares/Development/haskell/haskell-learn/codewars/.stack-work/install/aarch64-osx/5fcdde4fcb2d3e421d904e2b141cb989eb2b75c214fa897a4eb7fb6a71f865ec/9.4.5/share/aarch64-osx-ghc-9.4.5/codewars-0.1.0.0

hs-libraries:         HScodewars-0.1.0.0-BM3WsMXuX7NDIxbgGOC4Vh
depends:              base-4.17.1.0
haddock-interfaces:
    /Users/joaofelipesoares/Development/haskell/haskell-learn/codewars/.stack-work/install/aarch64-osx/5fcdde4fcb2d3e421d904e2b141cb989eb2b75c214fa897a4eb7fb6a71f865ec/9.4.5/doc/codewars-0.1.0.0/codewars.haddock

haddock-html:
    /Users/joaofelipesoares/Development/haskell/haskell-learn/codewars/.stack-work/install/aarch64-osx/5fcdde4fcb2d3e421d904e2b141cb989eb2b75c214fa897a4eb7fb6a71f865ec/9.4.5/doc/codewars-0.1.0.0
